//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPWScrumer.Entity.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScrumEntities : DbContext
    {
        public ScrumEntities()
            : base("name=ScrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Scrum> Scrums { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<UserScrum> UserScrums { get; set; }
        public DbSet<UserScrumDetailBlocker> UserScrumDetailBlockers { get; set; }
        public DbSet<UserScrumDetailTodayTask> UserScrumDetailTodayTasks { get; set; }
        public DbSet<UserScrumDetailYesterdayTask> UserScrumDetailYesterdayTasks { get; set; }
        public DbSet<UserScrumDetailParkingLot> UserScrumDetailParkingLots { get; set; }
    }
}
