//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrummer.Entity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserScrumDetailTodayTask
    {
        public int UserScrumDetailTodayTask1 { get; set; }
        public Nullable<int> UserScrumID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Task { get; set; }
        public string Priority { get; set; }
    
        public virtual UserScrum UserScrum { get; set; }
    }
}
